### ISSUE TITLE
Feature files become pink again when reopening the code, and does not tie to the step definition file

### ISSUE THREAD

**Issue by teckjbaggett** [reqnroll/Reqnroll.VisualStudio#15] opened 2024-03-15 05:34 UTC
### Used Visual Studio

Visual Studio 2022

### Are the latest Visual Studio updates installed?

Yes

### Issue Description

When I reopen a solution with reqroll feature files, it loses the association to the step definition files, over and over.  I have created a solution with 4 automated test projects of different types of tests, and this is occurring

### Steps to Reproduce

1. Add multiple Reqroll test projects with different names, generate a step definition file using the same BDD use case scenario names with the given when then statements
2. generate out step definition files for each project for the same feature name/acceptance criteria
3. The associations of step definitions files to the feature files are lost

**Comment by clrudolphi** [comment] 2024-03-15 13:58
To clarify, are you saying that the scenario names and steps are duplicates across multiple projects?

**Comment by gasparnagy** [comment] 2024-03-21 16:25
@teckjbaggett could you please include a screenshot that shows the problem?

**Comment by gasparnagy** [comment] 2024-04-08 16:25
Closing this as unable to reproduce now. @teckjbaggett if you can provide further details, please reopen the issue.

**Closed by gasparnagy** 2024-04-08 16:25 UTC
