### ISSUE TITLE
Can't rename a step with a cucumber expression but can with a regex

### ISSUE THREAD

**Issue by infinitejest69** [reqnroll/Reqnroll.VisualStudio#30] opened 2024-07-23 15:13 UTC
### Used Visual Studio

Visual Studio 2022

### Are the latest Visual Studio updates installed?

Yes

### Content of reqnroll.json (if present)

`{
  "livingDocGenerator": {
    "enabled": true,
    "filePath": "Results\\Execution\\TestExecution_{ProcessId}_{ThreadId}_{Now}.json"
  },
  "generator": {
    "addNonParallelizableMarkerForTags": [ "nonparallelizable" ]
  },
  "trace": {
    "traceSuccessfulSteps": false,
    "traceTimings": false,
    "coloredOutput": false
  }
}`

### Issue Description

Migrating from spec flow to Reqnroll and one small issue when refactoring some steps is you can't rename step that contains a cucumber expression but can if it uses the Regex

### Steps to Reproduce

When renaming this step:
```
       [StepDefinition(@"folder {string} is visible")]
       public async Task ThenISeeFolderIsCollapsed(string FolderName) => await Assertions.Expect(manager.PagesPage.PageTree.FolderByExactName(FolderName).ToBeVisibleAsync();

```
![image](https://github.com/user-attachments/assets/d3579217-50a1-43ec-be6e-c808001ce3c1)

But if you change the step to
```
       [StepDefinition(@"folder ""([^""]*)"" is visible")]
       public async Task ThenISeeFolderIsCollapsed(string FolderName) => await Assertions.Expect(manager.PagesPage.PageTree.FolderByExactName(FolderName).ToBeVisibleAsync();

```

Then it allows rename. also noticed the issues with using step definitions in another thread

**Comment by gasparnagy** [comment] 2024-07-26 13:58
This is unfortunately not yet supported. The rename is pretty limited currently. If you feel like you want to play with improving this, please let me know and I can give you hints to start.

I close this as "by design" (😢) for now...

**Closed by gasparnagy** 2024-07-26 13:58 UTC

**Comment by as3249762** [comment] 2024-10-11 14:43
Is this why the rename also doesn't work for Scenario Outlines with Examples. For example I get this error when I try to rename one:
![image](https://github.com/user-attachments/assets/1e6bfb60-1248-4098-9cc9-668ad8cf5efb)
